name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JDK_VERSION: 17

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.3.0
    - name: set up JDK ${{ env.JDK_VERSION }}
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '${{ env.JDK_VERSION }}'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Lint
      run: ./gradlew lint

    - name: Check and report lint results
      uses: hidakatsuya/action-report-android-lint@v1.2.3
      with:
        result-path: 'app/build/reports/lint-results-debug.xml'
        fail-on-warning: false
